import React from 'react'
import { Meteor } from 'meteor/meteor'
import ReactDOM from "react-dom"
import moment from 'moment'
import { Roles } from 'meteor/alanning:roles'
import { UploadImage, UploadCV } from './Upload.jsx'
import GetIcon from './GetIcon.jsx'
// import countries from './Countries.jsx'
import { Transition } from 'react-transition-group'
import { PrivacyPolicy, TermsOfAgreement } from './Termsandprivacy.jsx'
import { makeStyles } from '@mui/styles'
import Typography from '@material-ui/core/Typography'
import InputLabel from '@material-ui/core/InputLabel'
import Input from '@material-ui/core/Input'
import FormControl from '@material-ui/core/FormControl'
import FormHelperText from '@material-ui/core/FormHelperText'
import Grid from '@material-ui/core/Grid'
import Link from '@material-ui/core/Link'
import Paper from '@material-ui/core/Paper'
import Container from '@material-ui/core/Container'
import Divider from '@material-ui/core/Divider'
import Tooltip from '@material-ui/core/Tooltip'
import Select from '@material-ui/core/Select'
import DateFnsUtils from '@date-io/date-fns'
import TextField from '@material-ui/core/TextField'
import CircularProgress from '@material-ui/core/CircularProgress'
import MenuItem from '@material-ui/core/MenuItem'
import Checkbox from '@material-ui/core/Checkbox'
import InputAdornment from '@material-ui/core/InputAdornment'
import Button from '@material-ui/core/Button'
import IconButton from '@material-ui/core/IconButton'
import Table from '@material-ui/core/Table'
import TableBody from '@material-ui/core/TableBody'
import TableCell from '@material-ui/core/TableCell'
import TableContainer from '@material-ui/core/TableContainer'
import TableHead from '@material-ui/core/TableHead'
import TableRow from '@material-ui/core/TableRow'
import Stepper from '@material-ui/core/Stepper'
import Step from '@material-ui/core/Step'
import StepLabel from '@material-ui/core/StepLabel'
import StepContent from '@material-ui/core/StepContent'
import Slide from '@material-ui/core/Slide'
import Grow from "@material-ui/core/Grow"
import Box from '@material-ui/core/Box'
import Zoom from '@material-ui/core/Zoom'
import Fade from '@material-ui/core/Fade'
import Autocomplete from '@material-ui/lab/Autocomplete'
import ToggleButton from '@material-ui/lab/ToggleButton'
import ToggleButtonGroup from '@material-ui/lab/ToggleButtonGroup'
import Header from '../home/home.jsx'
import { Page404 } from './Page404.jsx'
import {
  CSSTransition,
  TransitionGroup,
} from 'react-transition-group';
import { useHistory } from 'react-router-dom'
import {
	MuiPickersUtilsProvider,
	KeyboardTimePicker,
	KeyboardDatePicker,
} from '@material-ui/pickers'
import { BrowserRouter as Router, Switch, Route, RouterLink, Redirect, useParams } from 'react-router-dom'
