import React from 'react'
import { Meteor } from 'meteor/meteor'
import ReactDOM from "react-dom"
import moment from 'moment'
import { Roles } from 'meteor/alanning:roles'
import { UploadImage, UploadCV } from './Upload.jsx'
import GetIcon from './GetIcon.jsx'
// import countries from './Countries.jsx'
import { Transition } from 'react-transition-group'
import { PrivacyPolicy, TermsOfAgreement } from './Termsandprivacy.jsx'
import { makeStyles } from '@mui/styles'
import Typography from '@mui/material/Typography'
import InputLabel from '@mui/material/InputLabel'
import Input from '@mui/material/Input'
import FormControl from '@mui/material/FormControl'
import FormHelperText from '@mui/material/FormHelperText'
import Grid from '@mui/material/Grid'
import Link from '@mui/material/Link'
import Paper from '@mui/material/Paper'
import Container from '@mui/material/Container'
import Divider from '@mui/material/Divider'
import Tooltip from '@mui/material/Tooltip'
import Select from '@mui/material/Select'
import DateFnsUtils from '@date-io/date-fns'
import TextField from '@mui/material/TextField'
import CircularProgress from '@mui/material/CircularProgress'
import MenuItem from '@mui/material/MenuItem'
import Checkbox from '@mui/material/Checkbox'
import InputAdornment from '@mui/material/InputAdornment'
import Button from '@mui/material/Button'
import IconButton from '@mui/material/IconButton'
import Table from '@mui/material/Table'
import TableBody from '@mui/material/TableBody'
import TableCell from '@mui/material/TableCell'
import TableContainer from '@mui/material/TableContainer'
import TableHead from '@mui/material/TableHead'
import TableRow from '@mui/material/TableRow'
import Stepper from '@mui/material/Stepper'
import Step from '@mui/material/Step'
import StepLabel from '@mui/material/StepLabel'
import StepContent from '@mui/material/StepContent'
import Slide from '@mui/material/Slide'
import Grow from "@mui/material/Grow"
import Box from '@mui/material/Box'
import Zoom from '@mui/material/Zoom'
import Fade from '@mui/material/Fade'
import Autocomplete from '@mui/lab/Autocomplete'
import ToggleButton from '@mui/lab/ToggleButton'
import ToggleButtonGroup from '@mui/lab/ToggleButtonGroup'
import Header from '../home/home.jsx'
import { Page404 } from './Page404.jsx'
import {
  CSSTransition,
  TransitionGroup,
} from 'react-transition-group';
import { useHistory } from 'react-router-dom'
import {
	MuiPickersUtilsProvider,
	KeyboardTimePicker,
	KeyboardDatePicker,
} from '@material-ui/pickers'
import { BrowserRouter as Router, Switch, Route, RouterLink, Redirect, useParams } from 'react-router-dom'
